package com.myspace.rulewithdmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AmountObj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("amount")
	private java.lang.Integer amount;

	public AmountObj() {
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public AmountObj(java.lang.Integer amount) {
		this.amount = amount;
	}

}